### ISSUE TITLE
update 6

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibAddonMenu#10]
I plan to finish and upload r17 tomorrow.
Things that still need to be done until then:
- [x] merge #9
- [x] update addon meta information
- [x] test with latest pts patch and many different addons
- [x] update documentation (wiki and addon description)
- [x] write changelog

Once the new version is ready, I will create an announcement on esoui, reddit and the official forums.

**Comment by sirinsidiator** [comment]
I wrote the announcement text:
>**LibAddonMenu-2.0r17 is now available**
>This version ensures that LibAddonMenu-2.0 is working correctly with Update 6 and will also work with Update 5.
>
>It also fixes an issue in how the loading of the library was handled.
>Right now older versions that are no longer compatible with the current API cause it to throw errors or prevent the addon settings from working.
>This fix cannot help with existing cases where such errors occur, but will prevent them from happening in the future.
>Because of this it is important that all addons update their copy of LAM to r17 as soon as possible.
>
>If you are an addon developer, you can download the latest version from [esoui](http://www.esoui.com/downloads/info7-LibAddonMenu.html) as usual.
>Also check out the new [LAM2 wiki on github](https://github.com/sirinsidiator/ESO-LibAddonMenu/wiki).

What do you think?

**Comment by merlight** [comment]
I have some trouble switching context between this fix and my branch which does it in a different way (checking fragment/control existence instead). So it took a while before I saw what it does to existing and future code. And I'm beginning to think that #9 takes the wrong approach. I will explain below with and example, but it's getting pretty long and I wanted to let you know there's something eerie around here ;)

**Comment by sirinsidiator** [comment]
I am waiting. Expecting a really long post ;)

**Comment by merlight** [comment]
Let's have a few independent addons with various LAM versions, that call RegisterAddonPanel before ADD_ON_LOADED. I will call these "broken", because by doing that, they were always asking for trouble. Let's then have some well-behaved add-ons with various LAM versions.

So, when addons are compiled and run (I mean the file-level run before events) in a particularly bad order with increasing LAM versions, we get:
brokenX/LAMv21 -> RegisterAddonPanel("brokenX") -> brokenY/LAMv22 -> RegisterAddonPanel("brokenY") -> brokenZ/LAMv23 etc.

If our `hasInitialized` is local, each premature register will call that version's Initialize. Not desirable, it will probably add multiple menu entries and spit duplicate control name errors. On the other hand, if we use `lam.hasInitialized`, then only "brokenX" will trigger LAMv21.Initialize. That's pretty bad, too, because if newer versions need to do something more during initialization, we will need `hasInitialized_22_features`, `hasInitialized_23_features`, etc. Imagine v23 adds a search box. It can't run its whole Initialize (that it would run if it was the only version installed). It must skip the parts v21 and v22 already did, and stick the searchbox somewhere. I don't think that's feasible in the long run.

The right solution would be to shaft broken addons. Instead of trying to play nice when they register panel too soon, LAM should tell them "Hey! Nobody knows the version you're calling is the most recent version the user has. Now go away, and come back after EVENT_ADD_ON_LOADED!" Of course we can inform the user we just rejected that addon (since it's unlikely the addon will understand and actually come back later), but we should absolutely not initialize/create controls. It's preferable to sacrifice one broken addon for the well-being of others (and I mean both devs and users).

Sadly I was not able to see this earlier. My branch does similar lazy initialization, but it surprisingly "just works" (well now at least) along with "broken" addons. That's only because I dropped the whole previous initialization and created a completely separate set of controls. Yes it's annoying that I now have 2 "Addon Settings" entries (with the current and the new style), but that's the "broken" addons' fault - they register their panel before the latest LAM is loaded. I only have to add pre-load rejection.

**Comment by sirinsidiator** [comment]
Read and now writing an equally long response ;)

**Comment by sirinsidiator** [comment]
That's actually the plan. We don't really play nicely with old pre-r17 versions and starting with r17, old code should never be run in the first place.
Let's take a look at how the old versions are currently handle loading.

Assume we have 2 old addons A and B and are playing on update 6.
A uses r14 and B uses r16

In cases when A gets loaded before B the initialization looks like this:

* run CreateAddonSettingsPanel in addon A
  - LAMSettingsPanelCreated is not yet set
  - the code is incompatible with the newer API and will throw an error
  - this is where execution stops
  
* run CreateAddonSettingsPanel in addon B
  - LAMSettingsPanelCreated is still not set
  - create the settings menu
  - LAMSettingsPanelCreated gets set
* run CreateAddonList

You will get an error and the addon menu will look strange in the end, but it works more or less.

When B gets loaded before A, LibStub will prevent r14 from getting initialized.

Now if we add a third addon C with r17, the same things will happen, but in addition it will do the following:
* check if LAMSettingsPanelCreated was already set and send a warning
  - this will work because new versions of LAM will only call initialize after all addons get loaded and the newest available code of LAM will get used
* run Initialization only when RegisterAddonPanel of the current version is run for the first time
  - hasInitialized is used to ensure that it will only get called once per version (backwards compatibility)
  - isSafeToInitialize is used to print a warning that a panel was registered too early, which should give addon devs a strong hint that they are doing something wrong

Let's add a fourth addon with r18.
We will also show the messages from before, but the Initialization of r17 will never happen, because RegisterAddonPanel gets replaced and whoever calls it will initialize r18 instead.

Once we have phased out all pre r17 versions, LAM should not do anything at all until the most up-to-date code has been loaded and RegisterAddonPanel is called for the first time.
So getting two entries in the settings should not be possible once all older versions have disappeared.

Now to come back to your concern about the initialization of outdated panels.
We simply cannot ensure that it won't get called.
When an addon uses an old version of LAM, we can try to reject it as much as we want in our newer version, but it will still happen because it calls RegisterAddonPanel of the older version.

The only way to do it, is to show a warning that an incompatible version was detected and hope that users report it often enough so that addon devs update their versions.
Once everything has transitioned to r17+, the warning should never show up again and everything should work as intended. Only the warning that a panel was registered too early will still show up when an author ignores it and uploads such an addon, but I hope they will get a few reports from users and fix it soon after.

This might sound a bit evil, but IMO it's the only way to get it to work.

**Comment by merlight** [comment]
Ok, got it.

**Comment by sirinsidiator** [comment]
r17 is on its way :)

**Comment by votan73** [comment]
Hi.

Is this just a bug fix version or why does it looking like the old style?
I'm a bit confused :)


Von: sirinsidiator <notifications@github.com>
Gesendet: Sonntag, 22. Februar 2015 18:02
An: sirinsidiator/ESO-LibAddonMenu
Cc: Jung, Markus | OGiTiX
Betreff: Re: [ESO-LibAddonMenu] update 6 (#10)


r17 is on its way :)

-

**Comment by sirinsidiator** [comment]
Yes, this version only contains the necessary fixes for update 6.
I think I mentioned that in the original thread on esoui?
The changes to the style will be part of r18 which is scheduled for March 15th.

**Comment by votan73** [comment]
Alright :)
I have not seen that, but that means nothing :D

CU

________________________________
Von: sirinsidiator <notifications@github.com>
Gesendet: Sonntag, 22. Februar 2015 19:27
An: sirinsidiator/ESO-LibAddonMenu
Cc: Jung, Markus | OGiTiX
Betreff: Re: [ESO-LibAddonMenu] update 6 (#10)


Yes, this version only contains the necessary fixes for update 6.
I think I mentioned that in the original thread on esoui?
The changes to the style will be part of r18 which is scheduled for March 15th.

-
