### ISSUE TITLE
ShownContextEntries parameter on combobox

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibAddonMenu#14]
Baertram asked for the following feature:

> Explanation:
> Currently the combobox always opens the context menu and shows all of the entries inside.
> If these entries are > 20 some screen resolutions won't fit the whole combobox context menu to the screen and the top part of the contetx menu is finally missing.
> 
> Idea:
> If you open the context menu of the combobox only "ShownContextEntries" will be shown at one page.
> All other entries will be accessible by a scrollbar anchored at the right side to the shown entries.
> If you scroll the entries only "ShownContextEntries" will always be visible in that context menu.
> 
> I think I remember Wykyyd's Chat Enhancement addon uses such a combobox for his "emotes list".
> 
> This would be really great as we could add many entries to the comboxboxes and ppl are able to select all of them properly, regardless what screen resolutiont hey are using.
> 
> Maybe > 20 entries are too much. But I like to provide a lot of possibilities (icons e.g.) that the users can choose from.

**Comment by merlight** [comment]
Yes I noticed that. I don't use FCO Item Saver, but have it installed since I spent some time debugging libFilters, and that list doesn't fit my screen. When I saw that I immediately thought there should be a `maxHeight` or `maxVisibleItems`, and use a scroll list instead of simple menu. It would even open possibility to customize rows, i.e. include an icon. Although in item saver in particular, I'd replace the dropdown with a custom control crafted for his specific usage (icon selector).

FCO Item Saver is also the one addon whose LAM panel's creation takes a bit too long. I didn't investigate why is that, but dropdown's UpdateChoices doesn't look right:
```diff
--- a/LibAddonMenu-2.0/LibAddonMenu-2.0/controls/dropdown.lua
+++ b/LibAddonMenu-2.0/LibAddonMenu-2.0/controls/dropdown.lua
@@ -68,8 +68,9 @@ local function UpdateChoices(control, choices)
        for i = 1, #choices do
                local entry = control.dropdown:CreateItemEntry(choices[i], DropdownCallback)
                entry.control = control
-               control.dropdown:AddItem(entry, not control.data.sort and ZO_COMBOBOX_SUPRESS_UPDATE)   --if sort type/order isn't specified, then don't sort
+               control.dropdown:AddItem(entry, ZO_COMBOBOX_SUPRESS_UPDATE)
        end
+       control.dropdown:UpdateItems()
 end
 
 local function GrabSortingInfo(sortInfo)
```

**Comment by votan73** [comment]
I know, it is a bit off topic here, but:
If people working "wrong" with the dropdown, we may should seperate them from implementation details.
For example we could make the settings property "choices" be callback-able: If it is a function, its return value is used. If it is a static table (like now), the table is used.
If the (returned) table contains strings, CreateItemEntry is call, otherwise the items are added the correct way.

Is clear, what I mean?

**Comment by sirinsidiator** [comment]
I'll close old ticket. Since #71 LAM allows the use of a scrollable dropdown.
